version: 1.0
provider:
  name: openfaas
  gateway: http://13.52.190.63:31112
functions:
  compress-image-node:
    lang: node18
    handler: ./compress-image-node
    image: compress-image-node:latest

